version: '3'

services:
  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend/places-sjsu
    ports:
      - "5173:5173"

